from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from yacs.config import CfgNode as CN

INTERNIMAGE_H = CN()
INTERNIMAGE_H.CORE_OP = 'DCNv3'
INTERNIMAGE_H.CHANNELS = 320
INTERNIMAGE_H.DEPTHS = [6, 6, 32, 6]
INTERNIMAGE_H.GROUPS = [10, 20, 40, 80]
INTERNIMAGE_H.MLP_RATIO = 4.
INTERNIMAGE_H.DROP_RATE = 0.
INTERNIMAGE_H.DROP_PATH_RATE = 0.5
INTERNIMAGE_H.norm_layer = 'LN'
INTERNIMAGE_H.LAYER_SCALE = None
INTERNIMAGE_H.OFFSET_SCALE = 1.0
INTERNIMAGE_H.POST_NORM = False
INTERNIMAGE_H.DW_KERNEL_SIZE = 5
INTERNIMAGE_H.RES_POST_NORM = True
INTERNIMAGE_H.LEVEL2_POST_NORM = True
INTERNIMAGE_H.LEVEL2_POST_NORM_BLOCK_IDS = [5, 11, 17, 23, 29]
INTERNIMAGE_H.CENTER_FEATURE_SCALE = True
INTERNIMAGE_H.REMOVE_CENTER = False
INTERNIMAGE_H.WITH_CP = True
INTERNIMAGE_H.OUT_INDICES = [0, 1, 2, 3]
INTERNIMAGE_H.OUT_FEATURES = ["res2", "res3", "res4", "res5"]

INTERNIMAGE_L = CN()
INTERNIMAGE_L.CORE_OP = 'DCNv3'
INTERNIMAGE_L.CHANNELS = 160
INTERNIMAGE_L.DEPTHS = [5, 5, 22, 5]
INTERNIMAGE_L.GROUPS = [10, 20, 40, 80]
INTERNIMAGE_L.MLP_RATIO = 4.
INTERNIMAGE_L.DROP_RATE = 0.
INTERNIMAGE_L.DROP_PATH_RATE = 0.4
INTERNIMAGE_L.norm_layer = 'LN'
INTERNIMAGE_L.LAYER_SCALE = None
INTERNIMAGE_L.OFFSET_SCALE = 2.0
INTERNIMAGE_L.POST_NORM = False
INTERNIMAGE_L.DW_KERNEL_SIZE = None
INTERNIMAGE_L.RES_POST_NORM = False
INTERNIMAGE_L.LEVEL2_POST_NORM = False
INTERNIMAGE_L.LEVEL2_POST_NORM_BLOCK_IDS = None
INTERNIMAGE_L.CENTER_FEATURE_SCALE = False
INTERNIMAGE_L.REMOVE_CENTER = False
INTERNIMAGE_L.WITH_CP = True
INTERNIMAGE_L.OUT_INDICES = [0, 1, 2, 3]
INTERNIMAGE_L.OUT_FEATURES = ["res2", "res3", "res4", "res5"]

INTERNIMAGE_XL = CN()
INTERNIMAGE_XL.CORE_OP = 'DCNv3'
INTERNIMAGE_XL.CHANNELS = 192
INTERNIMAGE_XL.DEPTHS = [5, 5, 24, 5]
INTERNIMAGE_XL.GROUPS = [12, 24, 48, 96]
INTERNIMAGE_XL.MLP_RATIO = 4.
INTERNIMAGE_XL.DROP_RATE = 0.
INTERNIMAGE_XL.DROP_PATH_RATE = 0.4
INTERNIMAGE_XL.norm_layer = 'LN'
INTERNIMAGE_XL.LAYER_SCALE = 1.0
INTERNIMAGE_XL.OFFSET_SCALE = 2.0
INTERNIMAGE_XL.POST_NORM = True
INTERNIMAGE_XL.DW_KERNEL_SIZE = None
INTERNIMAGE_XL.RES_POST_NORM = False
INTERNIMAGE_XL.LEVEL2_POST_NORM = False
INTERNIMAGE_XL.LEVEL2_POST_NORM_BLOCK_IDS = None
INTERNIMAGE_XL.CENTER_FEATURE_SCALE = False
INTERNIMAGE_XL.REMOVE_CENTER = False
INTERNIMAGE_XL.WITH_CP = True
INTERNIMAGE_XL.OUT_INDICES = [0, 1, 2, 3]
INTERNIMAGE_XL.OUT_FEATURES = ["res2", "res3", "res4", "res5"]
MODEL_CONFIGS = {
    'internimageH': INTERNIMAGE_H,
    'internimageL': INTERNIMAGE_L,
    'internimageXL': INTERNIMAGE_XL,
}